# Generated by Django 3.2.3 on 2021-06-04 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('costomer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='seller_shop_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('phone_number', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=50)),
                ('shop_address', models.CharField(max_length=100)),
                ('main_img', models.ImageField(upload_to=None)),
                ('password', models.CharField(max_length=50)),
                ('confirm_password', models.CharField(max_length=50)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='costomer.city')),
                ('shop_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.category')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='costomer.state')),
            ],
        ),
    ]
