# Generated by Django 3.2.3 on 2021-06-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller_shop_details',
            name='shop_description',
            field=models.TextField(default=''),
        ),
    ]
