# Generated by Django 3.2.3 on 2021-06-05 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_seller_shop_details_shop_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller_shop_details',
            name='shop_category',
            field=models.CharField(max_length=50),
        ),
    ]
