# Generated by Django 3.2.3 on 2021-06-05 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_alter_seller_shop_details_shop_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller_shop_details',
            name='main_img',
            field=models.ImageField(upload_to=''),
        ),
    ]
