# Generated by Django 3.2.3 on 2021-06-06 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0006_alter_products_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller_shop_details',
            name='main_img',
            field=models.ImageField(upload_to='seller/image'),
        ),
    ]
