# Generated by Django 3.2.3 on 2021-06-09 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0010_auto_20210610_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='seller_shop_details',
            name='main_img',
            field=models.ImageField(upload_to=''),
        ),
    ]
