# Generated by Django 3.2.3 on 2021-06-10 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0012_auto_20210610_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller_shop_details',
            name='seller_image',
            field=models.ImageField(blank=True, null=True, upload_to='seller'),
        ),
    ]
