# Generated by Django 3.2.3 on 2021-07-18 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0015_alter_seller_shop_details_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller_shop_details',
            name='full_name',
            field=models.CharField(max_length=50),
        ),
    ]
