# Generated by Django 3.2.3 on 2021-06-06 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costomer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('delivery_address', models.CharField(max_length=100)),
                ('costomer_name', models.CharField(max_length=50)),
                ('costomer_phone_number', models.CharField(max_length=50)),
                ('seller_name', models.CharField(max_length=50)),
                ('order_date_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='costomer_img',
            field=models.ImageField(blank=True, default='', upload_to='costomer/image'),
        ),
    ]
