# Generated by Django 3.2.3 on 2021-06-08 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costomer', '0002_auto_20210607_0121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_name',
        ),
    ]
