# Generated by Django 3.2.3 on 2021-06-10 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costomer', '0005_remove_order_order_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='costomer_img',
            field=models.FileField(upload_to='costomer'),
        ),
    ]
