# Generated by Django 3.2.3 on 2021-06-10 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costomer', '0006_alter_customer_costomer_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='costomer_img',
            field=models.ImageField(blank=True, null=True, upload_to='costomer'),
        ),
    ]
