# Generated by Django 3.2.3 on 2021-07-05 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costomer', '0014_auto_20210706_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.TextField(default=''),
        ),
    ]
