# Generated by Django 3.2.3 on 2021-07-18 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costomer', '0015_alter_order_delivery_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='full_name',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=50),
        ),
    ]
